/**
 * This file has been obtained from
 * SAPHRON - Statistical Applied PHysics through Random On-the-fly Numerics
 * https://github.com/hsidky/SAPHRON
 *
 * Copyright 2016 Hythem Sidky
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
*/
#pragma once 

#include "Requirement.h"

namespace Json
{
	//! Requirements on Integer values.
	/*!
	 * This class implements several types of integer requirements.
	 *
	 * \ingroup Json
	 */
	class IntegerRequirement : public Requirement
	{
	private:
		std::string _path; //!< Path for JSON path specification.
		int _multipleOf; //!< Multiple of requirement.
		int _min; //!< Lower bound for range requirement.
		int _max; //!< Upper bound for range requirement.
		bool _multSet; //!< If \c True multiple of is a requirement.
		bool _minSet; //!< If \c True lower bound is an active requirement.
		bool _maxSet; //!< If \c True upper bound is an active requirement.
		bool _exclMin; //!< If \c True lower bound is exclusive.
		bool _exclMax; //!< If \c True upper bound is exclusive.

	public:
		//! Constructor.
		IntegerRequirement() : 
		_path(), _multipleOf(0), _min(0), _max(0), _multSet(false), 
		_minSet(false), _maxSet(false), _exclMin(false), _exclMax(false)
		{}

		//! Reset requirement.
		virtual void Reset() override
		{
			_multipleOf = 0;
			_minSet = _maxSet = false;
			_exclMin = _exclMax = false; 
			_min = _max = 0;
			_multSet = false;
			ClearErrors();
			ClearNotices();
		}

		//! Parse JSON value to set up Requirement.
		/*!
		 * \param json JSON input value.
		 * \param path Path for JSON path specification.
		 */
		virtual void Parse(Value json, const std::string& path) override
		{
			Reset();
			
			_path = path;
			if(json.isMember("multipleOf") && json["multipleOf"].isInt())
			{
				_multSet = true;
				_multipleOf = json["multipleOf"].asInt();
			}

			if(json.isMember("minimum") && json["minimum"].isInt())
			{
				_minSet = true;
				_min = json["minimum"].asInt();
			}

			if(json.isMember("maximum") && json["maximum"].isInt())
			{
				_maxSet = true;
				_max = json["maximum"].asInt();
			}

			if(json.isMember("exclusiveMinimum") && json["exclusiveMinimum"].isBool())
			{
				_exclMin = json["exclusiveMinimum"].asBool();
			}

			if(json.isMember("exclusiveMaximum") && json["exclusiveMaximum"].isBool())
			{
				_exclMax = json["exclusiveMaximum"].asBool();
			}
		}

		//! Validate JSON value.
		/*!
		 * \param json JSON value to be validated.
		 * \param path Path for JSON path specification.
		 *
		 * Validates that the given JSON value is of type Integer and meets the
		 * requirements generated by IntegerRequirement::Parse(). If the
		 * requirements are not met, an error is generated.
		 */
		virtual void Validate(const Value& json, const std::string& path) override
		{
			if(!json.isInt())
			{
				PushError(path + ": Must be of type \"integer\".");
				return;
			}

			if(_multSet && (json.asInt() % _multipleOf != 0))
				PushError(path + ": Value must be a multiple of " + std::to_string(_multipleOf));

			if(_minSet)
			{
				if(_exclMin && json.asInt() <= _min)
					PushError(path + ": Value must be greater than " + std::to_string(_min));
				else if(json.asInt() < _min)
					PushError(path + ": Value cannot be less than " + std::to_string(_min));
			}

			if(_maxSet)
			{
				if(_exclMax && json.asInt() >= _max)
					PushError(path + ": Value must be less than " + std::to_string(_max));
				else if(json.asInt() > _max)
					PushError(path + ": Value cannot be greater than " + std::to_string(_max));
			}
		}
	};
}