/**
 * This file has been obtained from
 * SAPHRON - Statistical Applied PHysics through Random On-the-fly Numerics
 * https://github.com/hsidky/SAPHRON
 *
 * Copyright 2016 Hythem Sidky
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
*/
#pragma once 

#include "Requirement.h"

namespace Json
{
	//! Requirements on Integer values.
	/*!
	 * This class implements several types of integer requirements.
	 *
	 * \ingroup Json
	 */
	class IntegerRequirement : public Requirement
	{
	private:
		std::string path_; //!< Path for JSON path specification.
		int multipleOf_; //!< Multiple of requirement.
		int min_; //!< Lower bound for range requirement.
		int max_; //!< Upper bound for range requirement.
		bool multSet_; //!< If \c True multiple of is a requirement.
		bool minSet_; //!< If \c True lower bound is an active requirement.
		bool maxSet_; //!< If \c True upper bound is an active requirement.
		bool exclMin_; //!< If \c True lower bound is exclusive.
		bool exclMax_; //!< If \c True upper bound is exclusive.

	public:
		//! Constructor.
		IntegerRequirement() : 
		path_(), multipleOf_(0), min_(0), max_(0), multSet_(false), 
		minSet_(false), maxSet_(false), exclMin_(false), exclMax_(false)
		{}

		//! Reset requirement.
		virtual void Reset() override
		{
			multipleOf_ = 0;
			minSet_ = maxSet_ = false;
			exclMin_ = exclMax_ = false; 
			min_ = max_ = 0;
			multSet_ = false;
			ClearErrors();
			ClearNotices();
		}

		//! Parse JSON value to set up Requirement.
		/*!
		 * \param json JSON input value.
		 * \param path Path for JSON path specification.
		 */
		virtual void Parse(Value json, const std::string& path) override
		{
			Reset();
			
			path_ = path;
			if(json.isMember("multipleOf") && json["multipleOf"].isInt())
			{
				multSet_ = true;
				multipleOf_ = json["multipleOf"].asInt();
			}

			if(json.isMember("minimum") && json["minimum"].isInt())
			{
				minSet_ = true;
				min_ = json["minimum"].asInt();
			}

			if(json.isMember("maximum") && json["maximum"].isInt())
			{
				maxSet_ = true;
				max_ = json["maximum"].asInt();
			}

			if(json.isMember("exclusiveMinimum") && json["exclusiveMinimum"].isBool())
			{
				exclMin_ = json["exclusiveMinimum"].asBool();
			}

			if(json.isMember("exclusiveMaximum") && json["exclusiveMaximum"].isBool())
			{
				exclMax_ = json["exclusiveMaximum"].asBool();
			}
		}

		//! Validate JSON value.
		/*!
		 * \param json JSON value to be validated.
		 * \param path Path for JSON path specification.
		 *
		 * Validates that the given JSON value is of type Integer and meets the
		 * requirements generated by IntegerRequirement::Parse(). If the
		 * requirements are not met, an error is generated.
		 */
		virtual void Validate(const Value& json, const std::string& path) override
		{
			if(!json.isInt())
			{
				PushError(path + ": Must be of type \"integer\".");
				return;
			}

			if(multSet_ && (json.asInt() % multipleOf_ != 0))
				PushError(path + ": Value must be a multiple of " + std::to_string(multipleOf_));

			if(minSet_)
			{
				if(exclMin_ && json.asInt() <= min_)
					PushError(path + ": Value must be greater than " + std::to_string(min_));
				else if(json.asInt() < min_)
					PushError(path + ": Value cannot be less than " + std::to_string(min_));
			}

			if(maxSet_)
			{
				if(exclMax_ && json.asInt() >= max_)
					PushError(path + ": Value must be less than " + std::to_string(max_));
				else if(json.asInt() > max_)
					PushError(path + ": Value cannot be greater than " + std::to_string(max_));
			}
		}
	};
}